version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: clil-db
    environment:
      POSTGRES_DB: clil_db
      POSTGRES_USER: clil_user
      POSTGRES_PASSWORD: clil_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: